---
# Ansible Collection requirements for everything EXCEPT ansible.controller
# ansible.controller is dependent on the version of ansible!!!
# this is managed in the Containerfile

# these collections are compatible with ansible core 2.14.18 shipping with rhel 9.7
collections:
  - name: "ansible.utils"
    version: "<6.0.0"
  - name: "ansible.posix"
    version: "<1.6.0"
  - name: "ansible.netcommon"
    version: "<7.0.0"
  - name: "azure.azcollection"
    version: "<2.6.0"
  - name: "community.aws"
    version: "<8.0.0"
  - name: "community.crypto"
    version: "<3.0.0"
  - name: "community.general"
    version: "<10.0.0"
  - name: "community.vmware"
    version: "<4.0.0"
  - name: "containers.podman"    # Yay! actually only requires ansible-core 2.8
    version: "*"
  - name: "redhat.rhel_idm"
    version: ">=1.14.7"           # earlier versions fail with 'dns_over_tls' option error
  - name: "redhat.rhel_system_roles"
    version: "*"
  - name: "redhat.satellite"
    version: "*"
  - name: "redhat.satellite_operations"
    version: "*"
  - name: "vmware.vmware"
    version: "*"
