FROM registry.redhat.io/ubi9:latest
LABEL maintainer="Paul Armstrong <github:@parmstro>"
LABEL contributors="Paul Armstrong <github:@parmstro>, Mike Savage <github:@heatmiser>, Charles Shaw <github: @shawkingly>" 
LABEL description="The rhis-base container is built from rhel ubi9 and includes the binaries, python libraries and ansible collections required for rhis-builder. It is not designed to be used directly."
LABEL name="rhis-base"
LABEL summary="Provides the latest rhis-builder dependencies."
LABEL version="1.0"
# rpm requirements
ARG ANSIBLE_VER
RUN dnf -y install ansible-core git vim python3 python3-ipalib python3-gssapi python3-jmespath python3-pip bind-utils iputils bash-completion tmux
# python requirements

RUN mkdir -p /rhis
COPY sources/requirements.txt /rhis/requirements.txt
COPY sources/requirements.yml /rhis/requirements.yml
RUN /usr/bin/python3 -m pip install -r /rhis/requirements.txt

# ansible configuration
RUN mkdir -p /etc/ansible
COPY sources/ansible.cfg /etc/ansible/ansible.cfg

# Manage ansible.controller based on AAP target
RUN if [[ $ANSIBLE_VER == "2.5" ]]; then \
    echo "Installing ansible.controller collection for AAP 2.5"; \
    ansible-galaxy collection install ansible.controller:">=4.6"; \
    else \
    echo "Installing ansible.controller collection for AAP 2.4"; \
    ansible-galaxy collection install ansible.controller:"<4.6"; \
    fi

# install the remaining non-ansible-version dependent collections
RUN ansible-galaxy collection install ansible.netcommon
RUN ansible-galaxy collection install ansible.posix
RUN ansible-galaxy collection install azure.azcollection
RUN ansible-galaxy collection install community.aws
RUN ansible-galaxy collection install community.crypto
RUN ansible-galaxy collection install community.general
RUN ansible-galaxy collection install community.vmware
RUN ansible-galaxy collection install containers.podman
RUN ansible-galaxy collection install redhat.rhel_idm
RUN ansible-galaxy collection install redhat.rhel_system_roles
RUN ansible-galaxy collection install redhat.satellite
RUN ansible-galaxy collection install redhat.satellite_operations


# For optimized build
# This runs long and can fail in the middle 
# RUN ansible-galaxy collection install -r /rhis/requirements.yml

# Cleanup the ansible configuration
COPY sources/ansible.cfg.clean /etc/ansible/ansible.cfg
