ARG OS_VER
ARG ANSIBLE_VER
ARG RHIS_VER
ARG RHIS_BASE_VER

FROM quay.io/parmstro/rhis-base-${OS_VER}-${ANSIBLE_VER}:${RHIS_BASE_VER}
ARG RHIS_VER
ARG RHIS_BASE_VER
ENV VERSION=${RHIS_VER}
ENV BASE_VER=${RHIS_BASE_VER}

LABEL maintainer="Paul Armstrong <github:@parmstro>"
LABEL contributors="Paul Armstrong <github:@parmstro>, John Berninger <github:@jwbernin>, Cory McKee <github:@cojmckee>, Mike Savage <github:@heatmiser>, Charles Shaw <github: @shawkingly>" 
LABEL description="The rhis-provisioner container is built from rhel ubi9 and the rhis-builder set of repositories. It is design to make easy to implement the Red Hat Infrastructure Standard."
LABEL summary="Provides the latest build of rhis-builder repositories."

ENTRYPOINT ["/bin/bash", "-c", "echo '##########################################\nWelcome to the RHIS Provisioner container!' && echo 'RHIS Version: '$VERSION && echo 'Base Version: '$BASE_VER && exec /bin/bash"]
# rpm requirements

# copy our ipareplica patch to the proper location
COPY sources/ipareplica_test_patch.py /root/.ansible/collections/ansible_collections/redhat/rhel_idm/plugins/modules/ipareplica_test.py

# add the rhis builder repos
RUN mkdir -p /rhis
WORKDIR /rhis
RUN git clone https://github.com/parmstro/rhis-builder-idm.git
RUN git clone https://github.com/parmstro/rhis-builder-satellite.git
RUN git clone https://github.com/parmstro/rhis-builder-pipelines.git
RUN git clone https://github.com/parmstro/rhis-builder-aap.git
RUN git clone https://github.com/parmstro/rhis-builder-nbde.git
RUN git clone https://github.com/parmstro/rhis-builder-day-2-ops.git
RUN git clone https://github.com/parmstro/rhis-builder-ansible-ee.git
RUN git clone https://github.com/parmstro/rhis-builder-imagebuilder.git
RUN git clone https://github.com/parmstro/rhis-builder-yubi.git
RUN git clone https://github.com/parmstro/rhis-builder-convert2rhel.git
RUN git clone https://github.com/parmstro/rhis-builder-inventory.git

# Now make the folders for group_vars, host_vars and inventory files
RUN mkdir -p /rhis/vars/external_inventory
RUN mkdir -p /rhis/vars/external_tasks
RUN mkdir -p /rhis/vars/files
RUN mkdir -p /rhis/vars/group_vars
RUN mkdir -p /rhis/vars/host_vars
RUN mkdir -p /rhis/vars/vars
RUN mkdir -p /rhis/vars/vault

# This cleans up the repo vars folders and links each project to our volume directories
# we probably need to manage this for templates and files that we want to modify as well
COPY add_softlinks.yml /rhis/add_softlinks.yml
RUN chmod +x /rhis/add_softlinks.yml
RUN ansible-playbook add_softlinks.yml

# copy the reference information
COPY podman_commands.txt /rhis/podman_commands.txt
COPY rhis-builder_sample_commands.txt /rhis/rhis-builder_sample_commands.txt
COPY README.md /rhis/README.md

# copy the sample build scripts
COPY build_idm_primary.sh /rhis/build_idm_primary.sh
RUN chmod +x /rhis/build_idm_primary.sh

COPY build_idm_primary.sh /rhis/build_idm_replicas.sh
RUN chmod +x /rhis/build_idm_replicas.sh

COPY build_sat_primary_connected.sh /rhis/build_sat_primary_connected.sh
RUN chmod +x /rhis/build_sat_primary_connected.sh

COPY build_test_hosts.sh /rhis/build_test_hosts.sh
RUN chmod +x /rhis/build_test_hosts.sh

COPY destroy_test_hosts.sh /rhis/destroy_test_hosts.sh
RUN chmod +x /rhis/destroy_test_hosts.sh

COPY build_aap_controller24.sh /rhis/build_aap_controller24.sh
RUN chmod +x /rhis/build_aap_controller24.sh

COPY build_aap_controller24.sh /rhis/build_aap_hub24.sh
RUN chmod +x /rhis/build_aap_hub24.sh

# Cleanup the ansible configuration
COPY ansible.cfg.clean /etc/ansible/ansible.cfg
