ARG OS_VER
ARG ANSIBLE_VER
ARG RHIS_VER
ARG RHIS_BASE_VER
ARG RHIS_SCHEMA_VER
ARG PULL_PATH
ARG RHIS_BUILD

FROM ${PULL_PATH}/rhis-base-${OS_VER}-${ANSIBLE_VER}:${RHIS_BASE_VER}
ARG ANSIBLE_VER
ARG RHIS_VER
ARG RHIS_BASE_VER
ARG RHIS_SCHEMA_VER
ARG RHIS_BUILD
ENV ANS_VER=${ANSIBLE_VER}
ENV VERSION=${RHIS_VER}
ENV BASE_VER=${RHIS_BASE_VER}
ENV SCHEMA_VER=${RHIS_SCHEMA_VER}
ENV BUILD=${RHIS_BUILD}

MAINTAINER parmstro@redhat.com
LABEL maintainer="Paul Armstrong <github:@parmstro>"
LABEL contributors="Paul Armstrong <github:@parmstro>, John Berninger <github:@jwbernin>, Cory McKee <github:@cojmckee>, Mike Savage <github:@heatmiser>, Charles Shaw <github: @shawkingly>, Bryn Swan <github: @turtlesrock>, Charles Long <github: @mrclong>"
LABEL description="The rhis-provisioner container is built from rhel ubi9 and the rhis-builder set of repositories. It is design to make easy to implement the Red Hat Infrastructure Standard."
LABEL summary="Provides the latest build of rhis-builder repositories."

ENTRYPOINT ["/bin/bash", "-c", "echo '##########################################\nWelcome to the RHIS Provisioner container!' && echo 'RHIS Build: '$BUILD && echo 'Provisioner Version: '$VERSION && echo 'From Base Version: '$BASE_VER && echo 'For AAP Version: '$ANS_VER && echo 'RHIS Schema Version: '$SCHEMA_VER && exec /bin/bash"]
# rpm requirements

# copy our ipareplica patch to the proper location
COPY sources/ipareplica_test_patch.py /root/.ansible/collections/ansible_collections/redhat/rhel_idm/plugins/modules/ipareplica_test.py

# add the rhis builder repos
RUN mkdir -p /rhis
WORKDIR /rhis

# Now make the folders for group_vars, host_vars and inventory files
RUN mkdir -p /rhis/vars/external_inventory && \
    mkdir -p /rhis/vars/external_tasks && \
    mkdir -p /rhis/vars/files && \
    mkdir -p /rhis/vars/group_vars && \
    mkdir -p /rhis/vars/host_vars && \
    mkdir -p /rhis/vars/vars && \
    mkdir -p /rhis/vars/vault

# This cleans up the repo vars folders and links each project to our volume directories
# we probably need to manage this for templates and files that we want to modify as well
COPY configure_rhis_builder.yml /rhis/configure_rhis_builder.yml
RUN chmod +x /rhis/configure_rhis_builder.yml
RUN ansible-playbook /rhis/configure_rhis_builder.yml

# copy the reference information
# COPY podman_commands.txt /rhis/podman_commands.txt
# COPY rhis-builder_sample_commands.txt /rhis/rhis-builder_sample_commands.txt
# COPY sample_command.txt /rhis/sample_command.txt
COPY *.txt /rhis/
COPY README.md /rhis/README.md

# copy the sample build scripts
COPY build_idm_primary.sh /rhis/rhis-builder-idm/build_idm_primary.sh
COPY build_sat_primary_connected.sh /rhis/rhis-builder-satellite/build_sat_primary_connected.sh
COPY build_sat_1_capsules_satellite_pre.sh /rhis/rhis-builder-satellite/build_sat_1_capsules_satellite_pre.sh
COPY build_sat_2_capsules.sh /rhis/rhis-builder-satellite/build_sat_2_capsules.sh
COPY build_sat_3_capsules_satellite_post.sh /rhis/rhis-builder-satellite/build_sat_3_capsules_satellite_post.sh

COPY build_idm_replicas.sh /rhis/rhis-builder-idm/build_idm_replicas.sh
COPY build_aap24_controller.sh /rhis/rhis-builder-aap/build_aap24_controller.sh
COPY build_aap24_hub.sh /rhis/rhis-builder-aap/build_aap24_hub.sh
COPY build_aap25_controller.sh /rhis/rhis-builder-aap/build_aap25_controller.sh
COPY build_aap25_hub.sh /rhis/rhis-builder-aap/build_aap25_hub.sh
COPY deploy_rhel8_test_hosts.sh /rhis/rhis-builder-pipelines/deploy_rhel8_test_hosts.sh
COPY deploy_rhel9_test_hosts.sh /rhis/rhis-builder-pipelines/deploy_rhel9_test_hosts.sh
COPY deploy_rhel10_test_hosts.sh /rhis/rhis-builder-pipelines/deploy_rhel10_test_hosts.sh
COPY deploy_quadlet_hosts.sh /rhis/rhis-builder-pipelines/deploy_quadlet_hosts.sh
COPY deploy_sat_capsule_hosts.sh /rhis/rhis-builder-pipelines/deploy_sat_capsule_hosts.sh
COPY deploy_idm_replica_hosts.sh /rhis/rhis-builder-pipelines/deploy_idm_replica_hosts.sh
COPY deploy_aap24_hosts.sh /rhis/rhis-builder-pipelines/deploy_aap24_hosts.sh
COPY deploy_aap25_hosts.sh /rhis/rhis-builder-pipelines/deploy_aap25_hosts.sh
COPY destroy_test_hosts.sh /rhis/rhis-builder-pipelines/destroy_test_hosts.sh

# COPY *.sh /rhis/
RUN chmod +x /rhis/*/*.sh

# Cleanup the ansible configuration
COPY ansible.cfg.clean /etc/ansible/ansible.cfg
