---

- name: "Override Example Organization directories"
  hosts: localhost
  gather_facts: false
  vars:
    rhis_root_dir: "/rhis"
    default_inventory_link: "/rhis/vars/external_inventory"
    default_external_tasks_link: "/rhis/vars/external_tasks"
    default_files_link: "/rhis/vars/files"
    default_group_link: "/rhis/vars/group_vars"
    default_host_link: "/rhis/vars/host_vars"
    default_template_link: "/rhis/vars/templates"
    default_vars_link: "/rhis/vars/vars"
    default_vault_link: "/rhis/vars/vault"
    project_list:
      - name: "rhis-builder-idm"
      - name: "rhis-builder-satellite"
      - name: "rhis-builder-pipelines"
      - name: "rhis-builder-aap"
      - name: "rhis-builder-day-2-ops"
      - name: "rhis-builder-nbde"
      - name: "rhis-builder-imagebuilder"
      - name: "rhis-builder-yubi"
      - name: "rhis-builder-convert2rhel"
      # DO NOT INCLUDE rhis-builder-inventory... this is the definitive example directory

  tasks:

    - name: "Delete any inventory for each project"
      ansible.builtin.file:
        path: "{{ rhis_root_dir }}/{{ project.name }}/inventory"
        state: absent
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Link the inventory directory to the bind mount directory"
      ansible.builtin.file:
        src: "{{ default_inventory_link }}"
        dest: "{{ rhis_root_dir }}/{{ project.name }}/inventory"
        state: link
        mode: "0644"
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Delete any external_tasks directory for each project"
      ansible.builtin.file:
        path: "{{ rhis_root_dir }}/{{ project.name }}/external_tasks"
        state: absent
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Link the external_tasks directory to the bind mount directory"
      ansible.builtin.file:
        src: "{{ default_external_tasks_link }}"
        dest: "{{ rhis_root_dir }}/{{ project.name }}/external_tasks"
        state: link
        mode: "0644"
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Delete the files directories for each project"
      ansible.builtin.file:
        path: "{{ rhis_root_dir }}/{{ project.name }}/files"
        state: absent
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Link the files directory to the bind mount directory"
      ansible.builtin.file:
        src: "{{ default_files_link }}"
        dest: "{{ rhis_root_dir }}/{{ project.name }}/files"
        state: link
        mode: "0644"
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Delete the group_vars directories for each project"
      ansible.builtin.file:
        path: "{{ rhis_root_dir }}/{{ project.name }}/group_vars"
        state: absent
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Link the group_vars directory to the bind mount directory"
      ansible.builtin.file:
        src: "{{ default_group_link }}"
        dest: "{{ rhis_root_dir }}/{{ project.name }}/group_vars"
        state: link
        mode: "0644"
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Delete the host_vars directories for each project"
      ansible.builtin.file:
        path: "{{ rhis_root_dir }}/{{ project.name }}/host_vars"
        state: absent
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Link the host_vars directory to the bind mount directory"
      ansible.builtin.file:
        src: "{{ default_host_link }}"
        dest: "{{ rhis_root_dir }}/{{ project.name }}/host_vars"
        state: link
        mode: "0644"
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Delete the templates directories for each project"
      ansible.builtin.file:
        path: "{{ rhis_root_dir }}/{{ project.name }}/templates"
        state: absent
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Link the templates directory to the bind mount directory"
      ansible.builtin.file:
        src: "{{ default_template_link }}"
        dest: "{{ rhis_root_dir }}/{{ project.name }}/templates"
        state: link
        mode: "0644"
        force: true
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Delete any vars directory for each project"
      ansible.builtin.file:
        path: "{{ rhis_root_dir }}/{{ project.name }}/vars"
        state: absent
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Link the vars directory to the bind mount directory"
      ansible.builtin.file:
        src: "{{ default_vars_link }}"
        dest: "{{ rhis_root_dir }}/{{ project.name }}/vars"
        state: link
        mode: "0644"
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Delete any vault directory for each project"
      ansible.builtin.file:
        path: "{{ rhis_root_dir }}/{{ project.name }}/vault"
        state: absent
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project

    - name: "Link the inventory directory to the bind mount directory"
      ansible.builtin.file:
        src: "{{ default_vault_link }}"
        dest: "{{ rhis_root_dir }}/{{ project.name }}/vault"
        state: link
        mode: "0644"
      loop: "{{ project_list }}"
      loop_control:
        loop_var: project
